### ISSUE TITLE
readGDX(format = 'first_found') breaks on some .gdx files

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/gdx#2]
Using this file `/p/projects/rd3mod/gdx_file_breaking_readGDX.gdx`,

this works:
```R
str(readGDX('gdx_file_breaking_readGDX.gdx', 'v37_emiIndCCSmax', field = 'l'))
```

```
Formal class 'magpie' [package "magclass"] with 1 slot
  ..@ .Data: num [1:12, 1:40, 1:5] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..- attr(*, "dimnames")=List of 3
  .. .. ..$ all_regi: chr [1:12] "CAZ" "CHA" "EUR" "IND" ...
  .. .. ..$ ttot    : chr [1:40] "y1900" "y1905" "y1910" "y1915" ...
  .. .. ..$ emiInd37: chr [1:5] "co2cement_process" "co2cement" "co2chemicals" "co2steel" ...
```

but this doesn't:
```R
readGDX('gdx_file_breaking_readGDX.gdx', 'v37_emiIndCCSmax', field = 'l', 
         format = 'first_found')
```

```
NULL
Warning message:
In readGDX("gdx_file_breaking_readGDX.gdx", "v37_emiIndCCSmax",  :
  No element of v37_emiIndCCSmax found in GDX! NULL returned
```

Using the [current REMIND `input.gdx`](https://github.com/remindmodel/remind/blob/36d6fb0b86a5cc7b02dba2615e88775362bc1505/config/input.gdx) works, though.  Really weird interaction of `.gdx` file and `readGDX()` code.

**Comment by tscheypidi** [comment]
Apparrently, format="first_found" is case sensitive, while the other formats are not. In your specific case the name of the variable is `v37_emIIndCCSmax` so that readGDX('gdx_file_breaking_readGDX.gdx', 'v37_emIIndCCSmax', format="first_found") works.

I would have expected that all formats are case sensitive, but for the other formats we use a matchig function to also allow for automatic expansion of "*" (e.g. "v8_*" expands to all variable names of module 8). I guess that function makes the whole thing case insensitive. 

To avoid backwards compatibility issues I would suggest to keep it as it is.
